### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by hugomd** [hugomd/horloge#1]
**First timers only!** Please refrain from contributing to this if you're a seasoned contributor ✌️ 

This project is licensed under the [MIT license](https://choosealicense.com/licenses/mit/), but there's no `LICENSE` file in the repository 🤔

To close this issue:
* Fork this repository
* Add a new file called `LICENSE` and add the license text which you can find [here](https://choosealicense.com/licenses/mit/), and commit
* [Make a Pull Request](https://github.com/hugomd/horloge/compare) for this repository
* Celebrate! 🎉  (And accept feedback on the PR!)

If you have any questions, comment below! ✌️

**Comment by MyLocalCode** [comment]
Please close this issue as it is fixed in PR #4 

:octocat:

**Comment by hugomd** [comment]
@MyLocalCode Thanks for that! 🙏
