### ISSUE TITLE
Generate JSDoc documentation files

### ISSUE THREAD

**Issue by hugomd** [hugomd/horloge#2]
**First timers only!** Please refrain from contributing to this if you're a seasoned contributor ✌️ 

Generate [JSDoc](https://github.com/jsdoc3/jsdoc) documentation and store it in `docs/`, with either the [DocDash](https://github.com/clenemt/docdash) theme or the [minami](https://github.com/Nijikokun/minami) theme.

To do this, you'll need to:
* Add `jsdoc` as a development dependency (this is what `-D` does): `npm i -D jsdoc`
* Add a `doc` [npm script](https://docs.npmjs.com/misc/scripts) in [`package.json`](https://github.com/hugomd/horloge/blob/master/package.json) to use `jsdoc`
* Ensure the documentation is generated correctly in the `docs/` folder
* [Make a Pull Request](https://github.com/hugomd/horloge/compare) for this repository
* Celebrate! 🎉  (And accept feedback on the PR!)

If you have any questions, please comment below or ping me in a PR! ✌️

**Comment by octagonal** [comment]
I can do this :)

**Comment by hugomd** [comment]
Perfect, thanks @octagonal! 

🎃🎉

**Comment by octagonal** [comment]
Just a quick question @hugomd, should `docs/` be committed into the repo or added to `.gitignore`?

**Comment by hugomd** [comment]
@octagonal I think it would be best to commit them, so they can be popped onto GitHub Pages 👍 Is there a better way of doing it?

**Comment by octagonal** [comment]
No, that makes sense :). I opened a PR!
